### PR TITLE
Rename update-zblinks-api-->zbmath-links-api

### PR DESCRIPTION
**Pull request by physikerwelt**
Match the zblinks package spec, cf.

https://github.com/zbMATHOpen/linksApi/blob/bd52f22e8e479232a6fdfd878cf7e119b6ec2797/src/zb_links/api/link/helpers/link_helpers.py#L8

### CODE REVIEW

**Review by MatteoPetrera — COMMENTED** [review]
The argument of get_distribution() was correct. We want only to change the name of the matched_by column 

`    dist = get_distribution("update-zblinks-api")

    df_hist["matched_by"] = "zbmath-links-api"

    df_hist["matched_by_version"] = dist.version`

**Comment by physikerwelt** [comment]
@MatteoPetrera can you change it? I don't see where I get the df_hist object.

**Comment by physikerwelt** [comment]
Did that.

@MatteoPetrera you can also formally request changes on the pr. Then I can report that I followed your suggestions by just clicking a button. https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Comment by physikerwelt** [comment]
Two things. Changing the version is to my view a separate issue and thus should go to an extra pull request. In addition I think we should keep the package version. In production this version will be better readable.

**Review by MatteoPetrera — COMMENTED** [review]
Ok, I see your point. The last commit recovers the get_distribution() method

**Pull request merged**
